In [1]:
import numpy as np

In [4]:
problem_one_list_a = np.array([[0, 2], [-2, -5]])
problem_one_list_b = np.array([[6, -6], [3, 0]])
problem_one_answer = problem_one_list_a.dot(problem_one_list_b)
problem_one_answer

array([[  6,   0],
       [-27,  12]])

In [23]:
problem_two_list_a = np.array([[6], [-3]])
problem_two_list_b = np.array([-5, 9])
problem_two_answer = problem_two_list_b.dot(problem_two_list_a)
problem_two_answer

array([-57])

In [14]:
problem_three_list_a = np.array([[-5, -5], [-1, 2]])
problem_three_list_b = np.array([[-2, -3], [3, 5]])
problem_three_answer = problem_three_list_a.dot(problem_three_list_b)
problem_three_answer

array([[ -5, -10],
       [  8,  13]])

In [16]:
problem_four_list_a = np.array([[-3, 5], [-2, 1]])
problem_four_list_b = np.array([[6, -2], [1, -5]])
problem_four_answer = problem_four_list_a.dot(problem_four_list_b)
problem_four_answer

array([[-13, -19],
       [-11,  -1]])

In [21]:
problem_five_list_a = np.array([[0, 5], [-3, 1], [-5, 1]])
problem_five_list_b = np.array([[-4, 4], [-2, -4]])
problem_five_answer = problem_five_list_a.dot(problem_five_list_b)
problem_five_answer

array([[-10, -20],
       [ 10, -16],
       [ 18, -24]])

In [24]:
problem_six_list_a = np.array([[5, 3, 5], [1, 5, 0]])
problem_six_list_b = np.array([[-4, 2], [-3, 4], [3, -5]])
problem_six_answer = problem_six_list_a.dot(problem_six_list_b)
problem_six_answer

array([[-14,  -3],
       [-19,  22]])

In [26]:
problem_seven_list_a = np.array([[-5],[6],[0]])
problem_seven_list_b = np.array([3, -1])
problem_seven_answer = problem_seven_list_b.dot(problem_seven_list_a)
problem_seven_answer

ValueError: shapes (2,) and (3,1) not aligned: 2 (dim 0) != 3 (dim 0)

In [30]:
problem_eight_list_a = np.array([[3, 2, 5], [2, 3, 1]])
problem_eight_list_b = np.array([[4, 5],[5, -1],[-5, 6]])
problem_eight_answer = problem_eight_list_b.dot(problem_eight_list_a)
problem_eight_answer

array([[ 22,  23,  25],
       [ 13,   7,  24],
       [ -3,   8, -19]])

In [32]:
problem_nine_list_a = np.array([[3, -1], [-3, 6], [-6, -6]])
problem_nine_list_b = np.array([[-1, 6], [5, 4]])
problem_nine_answer = problem_nine_list_a.dot(problem_nine_list_b)
problem_nine_answer

array([[ -8,  14],
       [ 33,   6],
       [-24, -60]])

In [34]:
problem_ten_list_a = np.array([[5, 4], [2, -1]])
problem_ten_list_b = np.array([[-4],[3]])
problem_ten_answer = problem_ten_list_a.dot(problem_ten_list_b)
problem_ten_answer

array([[ -8],
       [-11]])

In [35]:
problem_eleven_list_a = np.array([[-1, 1, -1], [5, 2, -5], [6, -5, 1], [-5, 6, 0]])
problem_eleven_list_b = np.array([[6, 5], [5, -6], [6, 0]])
problem_eleven_answer = problem_eleven_list_a.dot(problem_eleven_list_b)
problem_eleven_answer

array([[ -7, -11],
       [ 10,  13],
       [ 17,  60],
       [  0, -61]])

In [36]:
problem_twelve_list_a = np.array([[-2, -6], [-4, 3], [5, 0], [4, -6]])
problem_twelve_list_b = np.array([[2, -2, 2],[2, 0, -3]])
problem_twelve_answer = problem_twelve_list_a.dot(problem_twelve_list_b)
problem_twelve_answer

array([[-16,   4,  14],
       [ -2,   8, -17],
       [ 10, -10,  10],
       [ -4,  -8,  26]])

In [37]:
problem_thirteen_list_a = np.array([])
problem_thirteen_list_b = np.array([])
problem_thirteen_answer = problem_thirteen_list_a.dot(problem_thirteen_list_b)
problem_thirteen_answer

array([[-16,   4,  14],
       [ -2,   8, -17],
       [ 10, -10,  10],
       [ -4,  -8,  26]])